export enum FinishedDrugs {
    GET_FINISHED_DRUG_ITEM = "GET_FINISHED_DRUG_ITEM",
    GET_FINISHED_DRUG_ITEM_SUCCESS = "GET_FINISHED_DRUG_ITEM_SUCCESS",
    GET_FINISHED_DRUG_ITEM_FAIL = "GET_FINISHED_DRUG_ITEM_FAIL",
    ADD_NEW_FINISHED_DRUG_ITEM = "ADD_NEW_FINISHED_DRUG_ITEM",
    ADD_NEW_FINISHED_DRUG_ITEM_SUCCESS = "ADD_NEW_FINISHED_DRUG_ITEM_SUCCESS",
    ADD_NEW_FINISHED_DRUG_ITEM_FAIL = "ADD_NEW_FINISHED_DRUG_ITEM_FAIL",
    EDIT_FINISHED_DRUG_ITEM = "EDIT_FINISHED_DRUG_ITEM",
    EDIT_FINISHED_DRUG_ITEM_SUCCESS = "EDIT_FINISHED_DRUG_ITEM_SUCCESS",
    EDIT_FINISHED_DRUG_ITEM_FAIL = "EDIT_FINISHED_DRUG_ITEM_FAIL",
    ADD_FINISHED_DRUG_RECORD_TO_TRANSACTION_HISTORY = "ADD_FINISHED_DRUG_RECORD_TO_TRANSACTION_HISTORY",
    ADD_FINISHED_DRUG_RECORD_TO_TRANSACTION_HISTORY_SUCCESS = "ADD_FINISHED_DRUG_RECORD_TO_TRANSACTION_HISTORY_SUCCESS",
    ADD_FINISHED_DRUG_RECORD_TO_TRANSACTION_HISTORY_SUCCESS_FAIL = "ADD_FINISHED_DRUG_RECORD_TO_TRANSACTION_HISTORY_SUCCESS_FAIL",
    DELETE_FINISHED_DRUG_ITEM = "DELETE_FINISHED_DRUG_ITEM",
    DELETE_FINISHED_DRUG_ITEM_SUCCESSFUL = "DELETE_FINISHED_DRUG_ITEM_SUCCESSFUL",
    DELETE_FINISHED_DRUG_ITEM_FAIL = "DELETE_FINISHED_DRUG_ITEM_FAIL"
  }