export enum GeneralStore {
    GET_GENERAL_STORE_ITEM = "GET_GENERAL_STORE_ITEM",
    GET_GENERAL_STORE_ITEM_SUCCESS = "GET_GENERAL_STORE_ITEM_SUCCESS",
    GET_GENERAL_STORE_ITEM_FAIL = "GET_GENERAL_STORE_ITEM_FAIL",
    ADD_NEW_GENERAL_STORE_ITEM_ITEM = "ADD_NEW_GENERAL_STORE_ITEM_ITEM",
    ADD_NEW_GENERAL_STORE_ITEM_SUCCESS = "ADD_NEW_GENERAL_STORE_ITEM_SUCCESS",
    ADD_NEW_GENERAL_STORE_ITEM_FAIL = "ADD_NEW_GENERAL_STORE_ITEM_FAIL",
    EDIT_GENERAL_STORE_ITEM = "EDIT_GENERAL_STORE_ITEM",
    EDIT_GENERAL_STORE_ITEM_SUCCESS = "EDIT_GENERAL_STORE_ITEM_SUCCESS",
    EDIT_GENERAL_STORE_ITEM_FAIL = "EDIT_GENERAL_STORE_ITEM_FAIL",
    ADD_GENERAL_STORE_RECORD_TO_TRANSACTION_HISTORY = "ADD_GENERAL_STORE_RECORD_TO_TRANSACTION_HISTORY",
    ADD_GENERAL_STORE_RECORD_TO_TRANSACTION_HISTORY_SUCCESS = "ADD_GENERAL_STORE_RECORD_TO_TRANSACTION_HISTORY_SUCCESS",
    ADD_GENERAL_STORE_RECORD_TO_TRANSACTION_HISTORY_FAIL = "ADD_GENERAL_STORE_RECORD_TO_TRANSACTION_HISTORY_FAIL",
    DELETE_GENERAL_STORE_ITEM = "DELETE_GENERAL_STORE_ITEM",
    DELETE_GENERAL_STORE_ITEM_SUCCESSFUL = "DELETE_GENERAL_STORE_ITEM_SUCCESSFUL",
    DELETE_GENERAL_STORE_ITEM_FAIL = "DELETE_GENERAL_STORE_ITEM_FAIL"
  }