export enum History {
    GET_ALL_HISTORY_RECORDS = "GET_ALL_HISTORY_RECORDS",
    GET_ALL_HISTORY_RECORDS_SUCCESS = "GET_ALL_HISTORY_RECORDS_SUCCESS",
    GET_ALL_HISTORY_RECORDS_FAIL = "GET_ALL_HISTORY_RECORDS_FAIL",
    DELETE_A_HISTORY_RECORD = "DELETE_A_HISTORY_RECORD",
    DELETE_A_HISTORY_RECORD_SUCCESS = "DELETE_A_HISTORY_RECORD_SUCCESS",
    DELETE_A_HISTORY_RECORD_FAIL = "DELETE_A_HISTORY_RECORD_FAIL"
  }