export enum Notification {
    GET_NOTIFICATION = "GET_NOTIFICATION",
    GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS",
    GET_NOTIFICATION_FAIL = "GET_NOTIFICATION_FAIL",
    MARK_ALL_MESSAGES_AS_READ = "MARK_ALL_MESSAGES_AS_READ",
    MARK_ALL_MESSAGES_AS_READ_SUCCESS = "MARK_ALL_MESSAGES_AS_READ_SUCCESS",
    MARK_ALL_MESSAGES_AS_READ_FAIL = "MARK_ALL_MESSAGES_AS_READ_FAIL"
}