export enum RawDrugs {
    GET_RAW_DRUG_ITEM = "GET_RAW_DRUG_ITEM",
    GET_RAW_DRUG_ITEM_SUCCESS = "GET_RAW_DRUG_ITEM_SUCCESS",
    GET_RAW_DRUG_ITEM_FAIL = "GET_RAW_DRUG_ITEM_FAIL",
    ADD_NEW_RAW_DRUG_ITEM = "ADD_NEW_RAW_DRUG_ITEM",
    ADD_NEW_RAW_DRUG_ITEM_SUCCESS = "ADD_NEW_RAW_DRUG_ITEM_SUCCESS",
    ADD_NEW_RAW_DRUG_ITEM_FAIL = "ADD_NEW_RAW_DRUG_ITEM_FAIL",
    EDIT_RAW_DRUG_ITEM = "EDIT_RAW_DRUG_ITEM",
    EDIT_RAW_DRUG_ITEM_SUCCESS = "EDIT_RAW_DRUG_ITEM_SUCCESS",
    EDIT_RAW_DRUG_ITEM_FAIL = "EDIT_RAW_DRUG_ITEM_FAIL"
  }