export enum RawDrugs {
    GET_RAW_DRUG_ITEM = "GET_RAW_DRUG_ITEM",
    GET_RAW_DRUG_ITEM_SUCCESS = "GET_RAW_DRUG_ITEM_SUCCESS",
    GET_RAW_DRUG_ITEM_FAIL = "GET_RAW_DRUG_ITEM_FAIL",
    ADD_NEW_RAW_DRUG_ITEM = "ADD_NEW_RAW_DRUG_ITEM",
    ADD_NEW_RAW_DRUG_ITEM_SUCCESS = "ADD_NEW_RAW_DRUG_ITEM_SUCCESS",
    ADD_NEW_RAW_DRUG_ITEM_FAIL = "ADD_NEW_RAW_DRUG_ITEM_FAIL",
    EDIT_RAW_DRUG_ITEM = "EDIT_RAW_DRUG_ITEM",
    EDIT_RAW_DRUG_ITEM_SUCCESS = "EDIT_RAW_DRUG_ITEM_SUCCESS",
    EDIT_RAW_DRUG_ITEM_FAIL = "EDIT_RAW_DRUG_ITEM_FAIL",
    ADD_RECORD_TO_TRANSACTION_HISTORY = "ADD_RECORD_TO_TRANSACTION_HISTORY",
    ADD_RECORD_TO_TRANSACTION_HISTORY_SUCCESS = "ADD_RECORD_TO_TRANSACTION_HISTORY_SUCCESS",
    ADD_RECORD_TO_TRANSACTION_HISTORY_SUCCESS_FAIL = "ADD_RECORD_TO_TRANSACTION_HISTORY_SUCCESS_FAIL",
    DELETE_RAW_DRUG_ITEM = "DELETE_RAW_DRUG_ITEM",
    DELETE_RAW_DRUG_ITEM_SUCCESSFUL = "DELETE_RAW_DRUG_ITEM_SUCCESSFUL",
    DELETE_RAW_DRUG_ITEM_FAIL = "DELETE_RAW_DRUG_ITEM_FAIL"
  }