export enum RegisteredUser {
    GET_REGISTERED_USER = "GET_REGISTERED_USER",
    GET_REGISTERED_USER_SUCCESS = "GET_REGISTERED_USER_SUCCESS",
    GET_REGISTERED_USER_FAIL = "GET_REGISTERED_USER_FAIL",
    DELETE_REGISTERED_USER = "DELETE_REGISTERED_USER",
    DELETE_REGISTERED_USER_SUCCESS = "DELETE_REGISTERED_USER_SUCCESS",
    DELETE_REGISTERED_USER_FAIL = "DELETE_REGISTERED_USER_FAIL"
}