export enum StoreKeeper {
    UPDATE_INVENTORY_RAW_DRUGS = "UPDATE_INVENTORY_RAW_DRUGS",
    UPDATE_INVENTORY_RAW_DRUGS_SUCCESS = "UPDATE_INVENTORY_RAW_DRUGS_SUCCESS",
    UPDATE_INVENTORY_RAW_DRUGS_FAIL = "UPDATE_INVENTORY_RAW_DRUGS_FAIL"
  }