export enum StoreKeeper {
    UPDATE_INVENTORY_RAW_DRUGS = "UPDATE_INVENTORY_RAW_DRUGS",
    UPDATE_INVENTORY_RAW_DRUGS_SUCCESS = "UPDATE_INVENTORY_RAW_DRUGS_SUCCESS",
    UPDATE_INVENTORY_RAW_DRUGS_FAIL = "UPDATE_INVENTORY_RAW_DRUGS_FAIL",
    UPDATE_INVENTORY_FINISHED_DRUGS = "UPDATE_INVENTORY_FINISHED_DRUGS",
    UPDATE_INVENTORY_FINISHED_DRUGS_SUCCESS = "UPDATE_INVENTORY_FINISHED_DRUGS_SUCCESS",
    UPDATE_INVENTORY_FINISHED_DRUGS_FAIL = "UPDATE_INVENTORY_FINISHED_DRUGS_FAIL",
    UPDATE_INVENTORY_GENERAL_STORE = "UPDATE_INVENTORY_GENERAL_STORE",
    UPDATE_INVENTORY_GENERAL_STORE_SUCCESS = "UPDATE_INVENTORY_GENERAL_STORE_SUCCESS",
    UPDATE_INVENTORY_GENERAL_STORE_FAIL = "UPDATE_INVENTORY_GENERAL_STORE_FAIL"
  }